import Foundation

struct ClassifiedItem: Sendable, Equatable {
    let kind: ItemKind
    let payload: Payload
    let previewText: String
    let searchableText: String
    let contentHash: String
    let detectedKinds: [String]

    enum Payload: Sendable, Equatable {
        case text(String)
        case image(pngData: Data, width: Int, height: Int)
        case files(urls: [URL], names: [String])
    }
}

enum SkipReason: Sendable, Equatable {
    case concealed
    case transient
    case autoGenerated
    case sensitive
    case excludedApp(bundleID: String)
    case noSupportedContent
}

enum ClassificationResult: Sendable, Equatable {
    case classified(ClassifiedItem)
    case skipped(SkipReason)
}
