import AppKit

struct PasteboardSnapshot: Sendable {
    let types: Set<NSPasteboard.PasteboardType>
    let string: String?
    let imageData: Data?
    let fileURLs: [URL]?
    let detectedKinds: Set<String>

    init(
        types: Set<NSPasteboard.PasteboardType>,
        string: String? = nil,
        imageData: Data? = nil,
        fileURLs: [URL]? = nil,
        detectedKinds: Set<String> = []
    ) {
        self.types = types
        self.string = string
        self.imageData = imageData
        self.fileURLs = fileURLs
        self.detectedKinds = detectedKinds
    }

    var sensitiveTypeReason: SkipReason? {
        for type in types {
            switch type.rawValue {
            case "org.nspasteboard.ConcealedType":
                return .concealed
            case "org.nspasteboard.TransientType":
                return .transient
            case "org.nspasteboard.AutoGeneratedType":
                return .autoGenerated
            case "com.apple.is-sensitive", "public.password":
                return .sensitive
            default:
                continue
            }
        }
        return nil
    }
}
